<h2>About AutoSearch</h2>
<p>The software powering this website was developed at the <a href="http://ivdnt.org" target="_blank">Dutch Language Institute</a>, and customized for Arabic by the <a href="https://www.esciencecenter.nl/" target="_blank">Netherlands eScience Center</a> and Utrecht University within the <a href="https://www.esciencecenter.nl/project/bridging-the-gap" target="_blank">Bridging the Gap project</a>.</p>
<p>
 The corpus search is powered by <a href="https://github.com/INL/BlackLab" target="_blank">BlackLab</a>, an open source Lucene-based corpus retrieval engine allowing fast and complex searches on large volumes of annotated text.
</p>
