<h2>About BlackLab ADH</h2>
<p>
  BlackLab ADH (Arabic Digital Humanities) provides access to several Arabic corpora.
</p>
<h3>Corpora</h3>
<p>
  The following corpora have been indexed in BlackLab. For each corpus, the raw text data is available.
</p>
<p>
  <ul>
    <li>Fiqh</li>
    <li>Dawa</li>
  </ul>
</p>
<h3>Software</h3>
<p>The software powering this website was developed at the <a href="http://ivdnt.org" target="_blank">Dutch Language Institute</a>, and customized for Arabic by the <a href="https://www.esciencecenter.nl/" target="_blank">Netherlands eScience Center</a> and Utrecht University within the <a href="https://www.esciencecenter.nl/project/bridging-the-gap" target="_blank">Bridging the Gap project</a>.</p>
<p>
 The corpus search is powered by <a href="https://github.com/INL/BlackLab" target="_blank">BlackLab</a>, an open source Lucene-based corpus retrieval engine allowing fast and complex searches on large volumes of annotated text.
</p>
<p>
  The front end is <a href="https://github.com/INL/corpus-frontend" target="_blank">BlackLab</a>, an open source front end for BlackLab.
</p>
<p>
  The pipelines for analyzing and indexing text are available in the <a href="https://github.com/arabic-digital-humanities/research-scripts" target="_blank">Arabic Digital Humanities research-scripts repository</a>. Please refer to the <a href="https://github.com/arabic-digital-humanities/research-scripts" target="_blank">README</a> for additional information.
</p>
