<style>
p.spacer { height: 1cm; }
p.endspacer { height: 5cm; }
.internal { display: none; }
</style>

<h1>AutoSearch help</h2>

<p class='spacer'><a name='help'></a>&nbsp;</p>

AutoSearch help is available in this <a target="_blank" href='https://docs.google.com/viewer?url=https://github.com/INL/corpus-frontend/raw/master/src/main/webapp/doc/AutoSearch-manual.pdf'>PDF manual</a>.

<p class='endspacer'><a name='end'></a>&nbsp;</p>
